export { default  as UserDisplay } from './UserDisplay'
export { default  as RepoDisplay } from './RepoDisplay'
export { default  as People } from './People'
export { default  as TopLanguages } from './TopLanguages'
export { default  as Error } from './Error'
export { default  as Spin } from './Spin'
